### ISSUE TITLE
Not 3D enough

### ISSUE THREAD

**Issue by PQCraft** [segfaultdev/tree#2]
3D when? :trollface:

**Comment by PQCraft** [comment]
BTW I saw this when scrolling through the recently updated AUR package list

**Comment by jmerono-saez** [comment]
Hey, CLIBASIC guy!

Well, even though this is obviously a joke, I actually made some tests with 3D celular automata sandbox games before creating tree. The two main reasons I didn't go with that is that placing blocks would be quite limited and performance.

**Comment by PQCraft** [comment]
F
